# Generated by Django 4.2.7 on 2024-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.TextField(default='', verbose_name='Номер группы')),
                ('group_name', models.TextField(blank=True, verbose_name='Название группы')),
                ('marks', models.TextField(blank=True, verbose_name='Примечание к группе')),
                ('students', models.TextField(default='', verbose_name='Состав группы')),
            ],
        ),
    ]
