# Generated by Django 4.2.7 on 2024-03-30 11:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcall_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Номер телефона')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('code', models.TextField(verbose_name='Отправленный код подтверждения')),
                ('date', models.TextField(verbose_name='Когда был запрошен код')),
                ('activated', models.BooleanField(default=False, verbose_name='Код был введён')),
                ('attempts', models.IntegerField(default=0, verbose_name='Количество попыток')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
            },
        ),
    ]
