# Generated by Django 4.2.7 on 2024-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.TextField(default='', verbose_name='Название занятия')),
                ('place', models.TextField(blank=True, verbose_name='Аудитория')),
                ('group', models.TextField(default='', verbose_name='Номер группы')),
                ('group_info', models.TextField(default='', verbose_name='Информация о группе (ФИО-Присутствие-Оценка-Примечание)')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
