# Generated by Django 4.2.7 on 2024-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonmodel_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='date',
            field=models.TextField(default='', verbose_name='Дата занятия'),
        ),
    ]
