# Generated by Django 4.2.7 on 2024-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='group',
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='group_id',
            field=models.TextField(default='', verbose_name='ID группы'),
        ),
    ]
