# Generated by Django 4.2.7 on 2024-06-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lessonmodel_group_lessonmodel_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='group_id',
            field=models.IntegerField(default=0, verbose_name='ID группы'),
        ),
    ]
