# Generated by Django 4.2.7 on 2024-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessonmodel_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='lesson_type',
            field=models.TextField(default='', verbose_name='Тип занятия~Hex цвет'),
        ),
    ]
