# Generated by Django 4.2.7 on 2024-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessonmodel_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='group_name',
            field=models.TextField(default='', verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='group_number',
            field=models.TextField(default='', verbose_name='Номер группы'),
        ),
    ]
