# Generated by Django 4.2.7 on 2024-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.TextField(blank=True, verbose_name='Оставленные отзывы (Название заведения~Текст отзыва~Оценка~Ссылка на заведение)'),
        ),
    ]
