# Generated by Django 4.2.7 on 2024-06-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_user',
        ),
    ]
